import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ricardo',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
      {
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 60,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'High Quality Product',
      },
      {
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 75,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'High Quality Product',
      },
      {
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'High Quality Product',
      },
      {
        name: 'Nike Slim Pants',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 60,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'High Quality Product',
      },
      {
        name: 'Puma Slim Pants',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 45,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'High Quality Product',
      },
      {
        name: 'Adidas Fit Pants',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 85,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'High Quality Product',
      },
    ],
  };
  export default data;